require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TomatoesController do

  # This should return the minimal set of attributes required to create a valid
  # Tomato. As you add validations to Tomato, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "body" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TomatoesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tomatoes as @tomatoes" do
      tomato = Tomato.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tomatoes).should eq([tomato])
    end
  end

  describe "GET show" do
    it "assigns the requested tomato as @tomato" do
      tomato = Tomato.create! valid_attributes
      get :show, {:id => tomato.to_param}, valid_session
      assigns(:tomato).should eq(tomato)
    end
  end

  describe "GET new" do
    it "assigns a new tomato as @tomato" do
      get :new, {}, valid_session
      assigns(:tomato).should be_a_new(Tomato)
    end
  end

  describe "GET edit" do
    it "assigns the requested tomato as @tomato" do
      tomato = Tomato.create! valid_attributes
      get :edit, {:id => tomato.to_param}, valid_session
      assigns(:tomato).should eq(tomato)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tomato" do
        expect {
          post :create, {:tomato => valid_attributes}, valid_session
        }.to change(Tomato, :count).by(1)
      end

      it "assigns a newly created tomato as @tomato" do
        post :create, {:tomato => valid_attributes}, valid_session
        assigns(:tomato).should be_a(Tomato)
        assigns(:tomato).should be_persisted
      end

      it "redirects to the created tomato" do
        post :create, {:tomato => valid_attributes}, valid_session
        response.should redirect_to(Tomato.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tomato as @tomato" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tomato.any_instance.stub(:save).and_return(false)
        post :create, {:tomato => { "body" => "invalid value" }}, valid_session
        assigns(:tomato).should be_a_new(Tomato)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tomato.any_instance.stub(:save).and_return(false)
        post :create, {:tomato => { "body" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tomato" do
        tomato = Tomato.create! valid_attributes
        # Assuming there are no other tomatoes in the database, this
        # specifies that the Tomato created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tomato.any_instance.should_receive(:update_attributes).with({ "body" => "MyText" })
        put :update, {:id => tomato.to_param, :tomato => { "body" => "MyText" }}, valid_session
      end

      it "assigns the requested tomato as @tomato" do
        tomato = Tomato.create! valid_attributes
        put :update, {:id => tomato.to_param, :tomato => valid_attributes}, valid_session
        assigns(:tomato).should eq(tomato)
      end

      it "redirects to the tomato" do
        tomato = Tomato.create! valid_attributes
        put :update, {:id => tomato.to_param, :tomato => valid_attributes}, valid_session
        response.should redirect_to(tomato)
      end
    end

    describe "with invalid params" do
      it "assigns the tomato as @tomato" do
        tomato = Tomato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tomato.any_instance.stub(:save).and_return(false)
        put :update, {:id => tomato.to_param, :tomato => { "body" => "invalid value" }}, valid_session
        assigns(:tomato).should eq(tomato)
      end

      it "re-renders the 'edit' template" do
        tomato = Tomato.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tomato.any_instance.stub(:save).and_return(false)
        put :update, {:id => tomato.to_param, :tomato => { "body" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tomato" do
      tomato = Tomato.create! valid_attributes
      expect {
        delete :destroy, {:id => tomato.to_param}, valid_session
      }.to change(Tomato, :count).by(-1)
    end

    it "redirects to the tomatoes list" do
      tomato = Tomato.create! valid_attributes
      delete :destroy, {:id => tomato.to_param}, valid_session
      response.should redirect_to(tomatoes_url)
    end
  end

end
